//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public Administrador()
        {
            this.Eventos = new HashSet<Evento>();
        }
    
        public int idAministrador { get; set; }
        public string Documento { get; set; }
        public string NombreCompleto { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
    
        public virtual ICollection<Evento> Eventos { get; set; }
    }
}
